<!DOCTYPE html>
<html>
<head>
    <?php require_once 'partials/head.phtml' ?>
    <title>Scores</title>
    <link rel="stylesheet" href="./css/normalize.css">
    <link rel="stylesheet" href="./css/homestyles.css">
    <link rel="icon" href="images/tabicon.png" sizes="192x192">
    <link rel="shortcut icon" href="images/tabicon.png">
    <link rel="apple-touch-icon" href="images/tabicon.png">
    <script defer src="./js/goToFilterDate.js"></script>
    <script defer src="./js/winningColors.js"></script>
</head>

<body>
<?php require_once 'partials/nav.phtml' ?>
<div class="main-content">
    <h3 class="listpage-heading">Score Comparison</h3>
    <span class="instructions">When comparing, scores are only added to total if both players played the same game on the same
        day</span>
    <span class="instructions">Low is good, high is bad. Win tally = day-by-day results.</span>
    <div class="overall-scores">

        <h3 class="listpage-heading">Overall Totals:</h3>

        <table id="score-compare-table">
            <thead>
            <tr>
                <th class="t-game-header">Player</th>
                <th class="center-in-t">Overall Score</th>
                <th class="center-in-t">Win Tally</th>
            </tr>
            </thead>
            <tbody>
            <tr id="cathy-row">
                <td>Cathy</td>
                <td id="cathy-row-totalscore" class="center-in-t" data-totalscore="<?php echo App\ViewHelpers\ScoresHelper::comparablePlayerTotalScore($comparableScores, 'Cathy') ?>">
                <?php echo App\ViewHelpers\ScoresHelper::comparablePlayerTotalScore($comparableScores, 'Cathy') ?>
                </td>
                <td id="cathy-row-wintally" class="center-in-t" data-wintally="<?php echo App\ViewHelpers\ScoresHelper::cathyWinTally($comparableScores, $dateList) ?>">
                    <?php echo App\ViewHelpers\ScoresHelper::cathyWinTally($comparableScores, $dateList) ?>
                </td>
            </tr>

            <tr id="jake-row">
                <td>Jake</td>
                <td id="jake-row-totalscore" class="center-in-t" data-totalscore="<?php echo App\ViewHelpers\ScoresHelper::comparablePlayerTotalScore($comparableScores, 'Jake') ?>">
                    <?php echo App\ViewHelpers\ScoresHelper::comparablePlayerTotalScore($comparableScores, 'Jake') ?>
                </td>
                <td id="jake-row-wintally" class="center-in-t" data-wintally="<?php echo App\ViewHelpers\ScoresHelper::jakeWinTally($comparableScores, $dateList) ?>">
                    <?php echo App\ViewHelpers\ScoresHelper::jakeWinTally($comparableScores, $dateList) ?>
                </td>
            </tr>

            </tbody>
        </table>

    </div>

    <span class="filter-header">Filter by date:</span>
    <div class="filter-box">
        <select id="date" name="date" required>
            <option value="">Select a date</option>
            <?php echo \App\ViewHelpers\ScoresHelper::datesDropdown($dateList) ?>
        </select>
        <button id="filter-button">Filter</button>
    </div>
    <div class="alert"></div>

    <h3 class="listpage-heading">Scores by Game:</h3>
    <table>
        <thead>
        <tr>
            <th class="t-game-header">Game</th>
            <th class="center-in-t">C-dawg</th>
            <th class="center-in-t">J-dawg</th>
            <th class="center-in-t">Bestest</th>
        </tr>
        </thead>
        <tbody>
        <?php echo App\ViewHelpers\ScoresHelper::displayGameScores($allScores, $gameList) ?>
        </tbody>
    </table>
</div>

<?php require_once 'partials/footer.phtml' ?>
</body>
</html>