<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Home</title>
    <link rel="stylesheet" href="./css/homestyles.css">
    <script defer src="./js/addGameScore.js"></script>

</head>
<body>
<a href="/scores">Go to Scores</a>

<div id="table-and-form-box">
    <div>
        <h1 id="home-heading">Game List</h1>
        <?php echo App\ViewHelpers\GamesListHelper::displayGameList($gameList) ?>
    </div>
    <div id="form-box">
        <h1>Submit a score</h1>
        <form id="scoreForm">
                <label for="gameName">Game Name:</label>
                <select id="game" name="game" required>
                    <?php echo \App\ViewHelpers\GamesListHelper::gameDropdown($gameList) ?>
                </select>
            <label for="player">Player:</label>
            <select id="player" name="player" required>
                <option value="Cathy">C-dawg</option>
                <option value="Jake">J-dawg</option>
            </select>

            <label for="score">Score:</label>
            <span class="instructions">Please add 2 points to maximum score if failed</span>
            <input type="number" id="score" name="score" required>
            <div id="invalidInt">
                <span>Invalid input. Please input a positive integer</span>
            </div>

            <label for="gameDate">Game Date:</label>
            <input type="date" id="gameDate" name="gameDate" required value="<?php echo date('Y-m-d'); ?>">

            <input type="submit" value="Submit" id="submit-button">
            <div id="submit-success">
                <span>Score successfully submitted</span>
            </div>
        </form>
    </div>
</div>


</body>
</html>
