<!DOCTYPE html>
<html>
<head>
    <?php require_once 'partials/head.phtml' ?>
    <title>Home</title>
    <link rel="stylesheet" href="./css/normalize.css">
    <link rel="stylesheet" href="./css/homestyles.css">
    <link rel="icon" href="images/tabicon.png" sizes="192x192">
    <link rel="shortcut icon" href="images/tabicon.png">
    <link rel="apple-touch-icon" href="images/tabicon.png">
    <script defer src="./js/addGameScore.js"></script>

</head>
<body>
<?php require_once 'partials/nav.phtml' ?>

<div id="list-and-form-box">
    <div>
        <h3 class="listpage-heading">Game List</h3>
        <div id="list-box">
            <?php echo App\ViewHelpers\GamesListHelper::displayGameList($gameList) ?>
        </div>
    </div>
    <div id="form-box">
        <h3 class="listpage-heading">Submit a Score</h3>
        <form id="scoreForm">
            <label for="gameName">Game:</label>
            <select id="game" name="game" required>
                <?php echo \App\ViewHelpers\GamesListHelper::gameDropdown($gameList) ?>
            </select>
            <label for="player">Player:</label>
            <select id="player" name="player" required>
                <option value="Cathy">C-dawg</option>
                <option value="Jake">J-dawg</option>
            </select>

            <label for="score">Score:</label>
            <span class="instructions">Please add 2 points to maximum score if failed</span>
            <input type="number" id="score" name="score" required>
            <div id="invalidInt">
                <span>Invalid input. Please input a positive integer</span>
            </div>

            <label for="gameDate">Game Date:</label>
            <input type="date" id="gameDate" name="gameDate" required value="<?php echo date('Y-m-d'); ?>">
            <div id="submit-div">
                <input type="submit" value="Submit" id="submit-button">
            </div>
            <div id="submit-success">
                <span>Score successfully submitted</span>
            </div>
        </form>
    </div>
</div>

<?php require_once 'partials/footer.phtml' ?>
</body>
</html>
