<!DOCTYPE html>
<html>
<head>
    <?php require_once 'partials/head.phtml'?>
    <title>Scores by Date</title>
    <link rel="stylesheet" href="../css/normalize.css">
    <link rel="stylesheet" href="../css/homestyles.css">
    <link rel="icon" href="images/tabicon.png" sizes="192x192">
    <link rel="shortcut icon" href="images/tabicon.png">
    <link rel="apple-touch-icon" href="images/tabicon.png">
    <script defer src="../js/filterDate.js"></script>
</head>

<body>
<?php require_once 'partials/nav.phtml'?>
<h1>Scores Filtered to <span id="selected-date"></span></h1>
<p class="instructions">Currently, scores are only added to total if both players played the same game on the same day</p>
<p class="instructions">The below scores a filtered by date</p>
<h2>Low is good, high is bad</h2>
<h3>Overall scores:</h3>
<label for="date">Dates:</label>
<select class="date" name="date" required>
    <option value="">Select a date</option>
    <?php echo \App\ViewHelpers\ScoresHelper::datesDropdown($dateList) ?>
</select>
<button class="filter-button">Filter</button>
<button class="clear-filter">Clear Date Filter</button>
<div class="alert"></div>
<?php echo App\ViewHelpers\ScoresHelper::displayTotalScore($allScores) ?>
<h3>Scores by Game:</h3>
<table>
    <thead>
    <tr>
        <th>Game</th>
        <th class="center-in-t">C-dawg</th>
        <th class="center-in-t">J-dawg</th>
        <th class="center-in-t">Bestest</th>
    </tr>
    </thead>
    <tbody>
    <?php echo App\ViewHelpers\ScoresHelper::displayGameScores($allScores, $gameList) ?>
    </tbody>
</table>
<?php require_once 'partials/footer.phtml' ?>

</body>
</html>