<!DOCTYPE html>
<html>
<head>
    <?php require_once 'partials/head.phtml' ?>
    <title>Scores by Date</title>
    <link rel="stylesheet" href="../css/normalize.css">
    <link rel="stylesheet" href="../css/homestyles.css">
    <link rel="icon" href="images/tabicon.png" sizes="192x192">
    <link rel="shortcut icon" href="images/tabicon.png">
    <link rel="apple-touch-icon" href="images/tabicon.png">
    <script defer src="../js/filterDate.js"></script>
</head>

<body>
<?php require_once 'partials/nav.phtml' ?>
<div class="main-content">
    <h3 class="listpage-heading">Scores filtered to <span id="selected-date"></span></h3>
    <span class="instructions">When comparing, scores are only added to total if both players played the same game on the same day</span>
    <span class="instructions">The below scores are filtered by date.</span>
    <span class="instructions">Low is good, high is bad.</span>

    <div class="overall-scores">
        <h3 class="listpage-heading">Overall scores:</h3>
        <?php echo App\ViewHelpers\ScoresHelper::displayTotalScore($allScores) ?>
    </div>
    <span class="filter-header">Filter by date:</span>

    <div class="filter-box">
        <select class="date" name="date" required>
            <option value="">Select a date</option>
            <?php echo \App\ViewHelpers\ScoresHelper::datesDropdown($dateList) ?>
        </select>
        <button class="filter-button">Filter</button>
        <button class="clear-filter">Clear Date Filter</button>
    </div>
    <div class="alert"></div>

    <h3 class="listpage-heading">Scores by Game:</h3>
    <table>
        <thead>
        <tr>
            <th class="t-game-header">Game</th>
            <th class="center-in-t">C-dawg</th>
            <th class="center-in-t">J-dawg</th>
            <th class="center-in-t">Bestest</th>
        </tr>
        </thead>
        <tbody>
        <?php echo App\ViewHelpers\ScoresHelper::displayGameScoresForDatePage($allScores, $gameList) ?>
        </tbody>
    </table>
</div>
<?php require_once 'partials/footer.phtml' ?>
</body>

</html>