<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Scores</title>

</head>
<body>

<h1>Scores</h1>
<p><a href="/">Home</a></p>
<h2>Low is good, high is bad</h2>
<?php echo App\ViewHelpers\ScoresHelper::displayTotalScore($allScores) ?>
<br>
<h4>Scores by Game:</h4>
<table>
    <tr>
        <th>Game</th>
        <th>Player One</th>
        <th>Player Two</th>
    </tr>
<?php echo App\ViewHelpers\ScoresHelper::displayGameScores($allScores, $gameList) ?>
</table>

</body>
</html>